export async function sendGmailReport(to: string, session: any, googleDocUrl?: string): Promise<{ success: boolean; error?: string }> {
  try {
    const info = session.extracted_info;
    const opportunities = session.opportunities || [];
    
    const subject = `🎯 Your AI Automation Audit Report - ${opportunities.length} Opportunities Found`;
    
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .opportunity { background: #f8f9fa; border-left: 4px solid #667eea; padding: 15px; margin: 10px 0; }
        .cta { background: #667eea; color: white; padding: 15px; text-align: center; margin: 20px 0; }
        .cta a { color: white; text-decoration: none; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎉 Your AI Automation Audit is Complete!</h1>
        <p>Personalized automation roadmap for ${contactInfo.company || discovery.industry || 'your business'}</p>
    </div>
    
    <div class="content">
        <h2>📊 Key Findings</h2>
        <ul>
            <li><strong>Industry:</strong> ${info?.industry || 'N/A'}</li>
            <li><strong>Team Size:</strong> ${info?.size || 'N/A'}</li>
            <li><strong>Opportunities Found:</strong> ${opportunities.length}</li>
            <li><strong>Total Annual Savings:</strong> $${opportunities.reduce((sum: number, opp: any) => sum + (opp.monthly_savings * 12), 0).toLocaleString()}</li>
        </ul>
        
        <h2>🚀 Top Automation Opportunities</h2>
        ${opportunities.slice(0, 3).map((opp: any, i: number) => `
        <div class="opportunity">
            <h3>${i + 1}. ${opp.name}</h3>
            <p><strong>Monthly Savings:</strong> $${opp.monthly_savings.toLocaleString()}</p>
            <p><strong>ROI:</strong> ${opp.roi_12m}% (12 months)</p>
            <p><strong>Implementation:</strong> ${opp.implementation_weeks} weeks</p>
        </div>
        `).join('')}
        
        ${googleDocUrl ? `
        <div class="cta">
            <h3>📄 View Your Complete Report</h3>
            <a href="${googleDocUrl}" target="_blank">Open Full Audit Report →</a>
            <p style="margin-top: 10px; font-size: 14px;">Click to view detailed analysis, implementation roadmap, and ROI calculations</p>
        </div>
        ` : ''}
        
        <h2>📋 Next Steps</h2>
        <ol>
            <li>Review your personalized opportunities above</li>
            <li>Schedule a 15-minute strategy call</li>
            <li>Start with quick wins for immediate impact</li>
        </ol>
        
        <p><strong>Questions?</strong> Reply to this email or contact us at ap3617180@gmail.com</p>
        
        <hr style="margin: 30px 0;">
        <p style="font-size: 12px; color: #666;">
            This audit was generated by our AI system based on your responses. 
            Results are estimates and actual implementation may vary.
        </p>
    </div>
</body>
</html>`;

    const textContent = `
🎯 Your AI Automation Audit Report

Hi there!

Your AI Opportunity Assessment is complete! We've identified ${opportunities.length} automation opportunities for ${info?.company || 'your business'}.

📊 KEY FINDINGS:
• Industry: ${info?.industry || 'N/A'}
• Team Size: ${info?.size || 'N/A'}
• Total Annual Savings: $${opportunities.reduce((sum: number, opp: any) => sum + (opp.monthly_savings * 12), 0).toLocaleString()}

🚀 TOP OPPORTUNITIES:
${opportunities.slice(0, 3).map((opp: any, i: number) => 
  `${i + 1}. ${opp.name}
   • Monthly Savings: $${opp.monthly_savings.toLocaleString()}
   • ROI: ${opp.roi_12m}% (12 months)
   • Implementation: ${opp.implementation_weeks} weeks`
).join('\n\n')}

${googleDocUrl ? `📄 FULL REPORT: ${googleDocUrl}` : ''}

📋 NEXT STEPS:
1. Review your personalized opportunities
2. Schedule a 15-minute strategy call
3. Start with quick wins for immediate impact

Questions? Reply to this email or contact us at ap3617180@gmail.com

Best regards,
AI Automation Team
`;

    // Use Gmail API to send email
    const emailData = {
      to,
      subject,
      html: htmlContent,
      text: textContent
    };

    const result = await sendViaGmailAPI(emailData);
    return result;
    
  } catch (error) {
    console.error('[Gmail] Failed to send email:', error);
    return { success: false, error: error.message };
  }
}

async function sendViaGmailAPI(emailData: any): Promise<{ success: boolean; error?: string }> {
  try {
    // Get access token using OAuth credentials
    let accessToken = process.env.GMAIL_ACCESS_TOKEN;
    
    if (!accessToken && process.env.GMAIL_REFRESH_TOKEN) {
      // Refresh access token
      const tokenResponse = await fetch('https://oauth2.googleapis.com/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          client_id: process.env.GOOGLE_CLIENT_ID!,
          client_secret: process.env.GOOGLE_CLIENT_SECRET!,
          refresh_token: process.env.GMAIL_REFRESH_TOKEN!,
          grant_type: 'refresh_token'
        })
      });
      
      const tokens = await tokenResponse.json();
      accessToken = tokens.access_token;
    }

    if (!accessToken) {
      throw new Error('No Gmail access token available');
    }

    // Create email message
    const message = [
      `To: ${emailData.to}`,
      `Subject: ${emailData.subject}`,
      `Content-Type: text/html; charset=utf-8`,
      '',
      emailData.html
    ].join('\n');

    const encodedMessage = Buffer.from(message).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

    const response = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ raw: encodedMessage })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gmail API failed: ${response.statusText} - ${errorText}`);
    }

    const result = await response.json();
    console.log('[Gmail] Email sent successfully:', result.id);
    return { success: true };

  } catch (error) {
    console.error('[Gmail] Error:', error);
    return { success: false, error: error.message };
  }
}