// Using direct API calls instead of googleapis library for serverless

const GOOGLE_DOCS_TEMPLATE = `AI AUTOMATION AUDIT REPORT

{{report_content}}

---
COMPANY DETAILS
Company: {{company}}
Industry: {{industry}}
Team Size: {{size}}
Contact: {{contact_name}} ({{contact_email}})
Date Generated: {{date}}

OPPORTUNITY SUMMARY
{{opportunities_summary}}

FINANCIAL OVERVIEW
{{financial_summary}}

---
This comprehensive audit report was generated by AI Automation Audit System
For questions or implementation support, contact: {{contact_email}}
`;

export async function createGoogleDoc(auditData: any): Promise<{ success: boolean; docUrl?: string; error?: string }> {
  try {
    const accessToken = await getAccessToken();
    
    if (!accessToken) {
      return { success: false, error: 'No Google access token available' };
    }

    // Create document
    const createResponse = await fetch('https://docs.googleapis.com/v1/documents', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: `AI Automation Audit - ${contactInfo.company || discovery.industry || 'Client Company'} - ${new Date().toLocaleDateString()}`
      })
    });

    if (!createResponse.ok) {
      throw new Error(`Failed to create document: ${createResponse.statusText}`);
    }

    const doc = await createResponse.json();
    const docId = doc.documentId;

    // Extract data from audit session
    const discovery = auditData.extracted_info?.discovery || {};
    const painPoints = auditData.extracted_info?.pain_points || {};
    const contactInfo = auditData.extracted_info?.contact_info || {};
    
    // Prepare comprehensive content
    const totalMonthlySavings = auditData.opportunities?.reduce((sum: number, opp: any) => sum + (opp.monthly_savings || 0), 0) || 0;
    const totalAnnualSavings = totalMonthlySavings * 12;
    const totalImplementationCost = auditData.opportunities?.reduce((sum: number, opp: any) => sum + (opp.base_cost || 5000), 0) || 0;
    
    const content = GOOGLE_DOCS_TEMPLATE
      .replace('{{report_content}}', auditData.report_content || 'Detailed report content not available')
      .replace('{{company}}', contactInfo.company || discovery.industry || 'Client Company')
      .replace('{{industry}}', discovery.industry || 'Not specified')
      .replace('{{size}}', discovery.companySize || 'Not specified')
      .replace('{{contact_name}}', contactInfo.name || 'Contact')
      .replace('{{contact_email}}', contactInfo.email || auditData.email || 'Not provided')
      .replace('{{date}}', new Date().toLocaleDateString())
      .replace('{{opportunities_summary}}', auditData.opportunities?.map((opp: any, i: number) => 
        `${i + 1}. ${opp.name}\n   Category: ${opp.category || 'General'}\n   Monthly Savings: $${(opp.monthly_savings || 0).toLocaleString()}\n   Annual ROI: ${opp.roi_12m || 0}%\n   Implementation Time: ${opp.implementation_weeks || 'TBD'} weeks\n   Priority: ${opp.quadrant || 'Medium'}\n`
      ).join('\n') || 'No opportunities identified')
      .replace('{{financial_summary}}', `FINANCIAL IMPACT SUMMARY:\n\nTotal Monthly Savings: $${totalMonthlySavings.toLocaleString()}\nTotal Annual Savings: $${totalAnnualSavings.toLocaleString()}\nEstimated Implementation Investment: $${totalImplementationCost.toLocaleString()}\nPayback Period: ${Math.round(totalImplementationCost / (totalMonthlySavings || 1))} months\nNet ROI (12 months): ${Math.round(((totalAnnualSavings - totalImplementationCost) / totalImplementationCost) * 100)}%\n\nBREAKDOWN BY OPPORTUNITY:\n${auditData.opportunities?.map((opp: any) => `- ${opp.name}: $${((opp.monthly_savings || 0) * 12).toLocaleString()} annual savings`).join('\n') || 'No detailed breakdown available'}`);

    // Insert content
    const updateResponse = await fetch(`https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        requests: [{
          insertText: {
            location: { index: 1 },
            text: content
          }
        }]
      })
    });

    if (!updateResponse.ok) {
      throw new Error(`Failed to update document: ${updateResponse.statusText}`);
    }

    // Make document public
    const driveResponse = await fetch(`https://www.googleapis.com/drive/v3/files/${docId}/permissions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        role: 'reader',
        type: 'anyone'
      })
    });

    const docUrl = `https://docs.google.com/document/d/${docId}/edit`;
    console.log('[Google Docs] Document created:', docUrl);
    
    return { success: true, docUrl };



  } catch (error) {
    console.error('[Google Docs] Creation failed:', error);
    return { success: false, error: error.message };
  }
}

async function getAccessToken(): Promise<string | null> {
  if (process.env.GOOGLE_REFRESH_TOKEN) {
    try {
      const response = await fetch('https://oauth2.googleapis.com/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          client_id: process.env.GOOGLE_CLIENT_ID!,
          client_secret: process.env.GOOGLE_CLIENT_SECRET!,
          refresh_token: process.env.GOOGLE_REFRESH_TOKEN!,
          grant_type: 'refresh_token'
        })
      });
      
      if (!response.ok) {
        throw new Error(`Token refresh failed: ${response.statusText}`);
      }
      
      const tokens = await response.json();
      return tokens.access_token;
    } catch (error) {
      console.error('[Google Auth] Refresh token failed:', error);
      throw error;
    }
  }
  
  throw new Error('GOOGLE_REFRESH_TOKEN not found in environment');
}